<?php

/**
 *
 * @copyright  2019-2020 objectivejs.org
 * @version    2
 * @link       http://www.objectivejs.org
 */
?>
<?php $text='Objective.js'; ?>
<?php $fontlist=array('Acme', 'Fugaz One', 'Inconsolata', 'Lobster', 'Long Cang', 'Modak', 'Roboto', 'Play', 'Slackey'); ?>
<?php $font='Roboto'; ?>
<?php $fontSize=32; ?>
<?php $color='#333'; ?>
<?php $bg='#fd1'; ?>
<?php foreach($fontlist as $f): ?><?php head('font', $f); ?><?php endforeach; ?>
<?php $id=uniqid('id'); ?>
<style>
.test_display {
	width: 240px;
	height: 135px;
	display: flex;
	align-items: center;
	justify-content: center;
	background: <?php echo $bg; ?>;
	color: <?php echo $color; ?>;
	font-family: "<?php echo $font; ?>", sans-serif;
	font-size: <?php echo $fontSize; ?>px;
	margin-bottom: 10px;
	border-radius: 3px;
}
</style>
<div id="<?php echo $id; ?>" class="noprint">
<div class="test_display"><?php echo $text; ?></div>
<div class="ojs">
<div class="options_panel">
<?php if (true): ?>
<select size="1">
<?php foreach($fontlist as $f): ?>
<option value="<?php echo $f; ?>"<?php if ($f == $font): ?> selected="selected"<?php  endif; ?>><?php echo $f; ?></option>
<?php endforeach; ?>
</select>
<?php endif; ?>
</div>
</div>
</div>
<?php head('javascript', '/objectivejs/Objective.js'); ?>
<?php head('javascript', '/objectivejs/Responder.js'); ?>
<?php head('javascript', '/objectivejs/View.js'); ?>
<?php head('javascript', '/objectivejs/Inspector.js'); ?>
<?php head('javascript', '/objectivejs/SelectInspector.js'); ?>
<script>
function Tester(display, inspector) {
	Responder.call(this);

	this._display = display;

	inspector.addNextResponder(this);

	this._inspector = inspector;
}

Tester.prototype = Object.create(Responder.prototype);

Object.defineProperty(Tester.prototype, 'constructor', { value: Tester, enumerable: false, writable: true });

Tester.prototype.inspectorValueChanged = function(sender) {
	if (sender === this._inspector)
		this._display.style.fontFamily = `"${sender.get()}", sans-serif`;

	return true;
}
</script>
<script>
const fontnames = [<?php echo implode(',', array_map(function($s) { return "'$s'"; }, $fontlist)); ?>];

const inspector = new SelectInspector('<?php echo $font; ?>', { tags: fontnames });

const container = document.querySelector('#<?php echo $id; ?>');

const display = container.querySelector('.test_display');

<?php if (true): ?>
inspector.setManagedWidget(container.querySelector('select')).resetWidget();
<?php else: ?>
inspector.createManagedWidget(container.querySelector('.options_panel')).resetWidget();
<?php endif; ?>

const tester = new Tester(display, inspector);
</script>
