<?php

/**
 *
 * @copyright  2020 objectivejs.org
 * @version    1
 * @link       http://www.objectivejs.org
 */
?>
<?php $text='Objective.js'; ?>
<?php $fontlist=array('Acme', 'Fugaz One', 'Inconsolata', 'Lobster', 'Long Cang', 'Modak', 'Open Sans', 'Play', 'Slackey'); ?>
<?php $font='Open Sans'; ?>
<?php $fontSize=32; ?>
<?php $color='#333'; ?>
<?php $bg='#fd1'; ?>
<?php $minlen=2; ?>
<?php $maxlen=12; ?>
<?php foreach($fontlist as $f): ?><?php head('font', $f); ?><?php endforeach; ?>
<?php $id=uniqid('id'); ?>
<style>
.test_display {
	width: 240px;
	height: 135px;
	display: flex;
	align-items: center;
	justify-content: center;
	background: <?php echo $bg; ?>;
	color: <?php echo $color; ?>;
	font-family: "<?php echo $font; ?>", sans-serif;
	font-size: <?php echo $fontSize; ?>px;
	margin-bottom: 10px;
	border-radius: 3px;
}
</style>
<div id="<?php echo $id; ?>" class="noprint">
<div class="test_display"><?php echo $text; ?></div>
<div class="ojs">
<div>
<span>
<input id="text_input" type="text" size="10" maxlength="<?php echo $maxlen; ?>" spellcheck="false"/>
<select id="text_font" size="1">
<?php foreach($fontlist as $f): ?>
<option value="<?php echo $f; ?>"<?php if ($f == $font): ?> selected="selected"<?php  endif; ?>><?php echo $f; ?></option>
<?php endforeach; ?>
</select>
<span class="nowrap"><input id="text_italic" type="checkbox"/><span class="btn_edit btn_i" title="">I</span></span>
</span>
</div>
</div>
</div>
<?php head('javascript', '/objectivejs/Objective.js') ?>
<?php head('javascript', '/objectivejs/Responder.js') ?>
<?php head('javascript', '/objectivejs/View.js') ?>
<?php head('javascript', '/objectivejs/Inspector.js') ?>
<?php head('javascript', '/objectivejs/SelectInspector.js') ?>
<?php head('javascript', '/objectivejs/StringInspector.js') ?>
<?php head('javascript', '/objectivejs/BooleanInspector.js') ?>
<?php head('javascript', '/objectivejs/SequenceInspector.js') ?>
<script>
function Tester(display, inspector) {
	Responder.call(this);

	this._display = display;

	inspector.addNextResponder(this);

	this._inspector = inspector;
}

Tester.prototype = Object.create(Responder.prototype);

Object.defineProperty(Tester.prototype, 'constructor', { value: Tester, enumerable: false, writable: true });

Tester.prototype.inspectorValueChanged = function(sender) {
	if (sender === this._inspector) {
		const {font, text, italic} = sender.get();

		this._display.style.fontStyle = italic ? 'italic' : 'normal';
		this._display.style.fontFamily = `"${font}", sans-serif`;
		this._display.innerHTML = `<span>${text}</span>`;
	}

	return true;
}
</script>
<script>
const fontnames = [<?php echo implode(',', array_map(function($s) { return "'$s'"; }, $fontlist)); ?>];

const fontInspector = new SelectInspector('<?php echo $font; ?>', { tags: fontnames });

const textInspector = new StringInspector('<?php echo $text; ?>', { min: <?php echo $minlen; ?>, max: <?php echo $maxlen; ?>, trim: true, required: true, escapeHTML: true });

const italicInspector = new BooleanInspector();

const container = document.querySelector('#<?php echo $id; ?>');

const display = container.querySelector('.test_display');

fontInspector.setManagedWidget(container.querySelector('#text_font')).resetWidget();
textInspector.setManagedWidget(container.querySelector('#text_input')).resetWidget();
italicInspector.setManagedWidget(container.querySelector('#text_italic')).resetWidget();

const inspector = new SequenceInspector({ font: fontInspector, text: textInspector, italic: italicInspector });

const tester = new Tester(display, inspector);
</script>