<?php

/**
 *
 * @copyright  2019-2020 objectivejs.org
 * @version    2
 * @link       http://www.objectivejs.org
 */
?>
<?php $text='Objective.js'; ?>
<?php $font='Roboto'; ?>
<?php $fontSize=32; ?>
<?php $color='#333'; ?>
<?php $bg='#fd1'; ?>
<?php head('font', $font); ?>
<?php $id=uniqid('id'); ?>
<style>
.test_display {
	width: 240px;
	height: 135px;
	display: flex;
	align-items: center;
	justify-content: center;
	background: <?php echo $bg; ?>;
	color: <?php echo $color; ?>;
	font-family: "<?php echo $font; ?>", sans-serif;
	font-size: <?php echo $fontSize; ?>px;
	margin-bottom: 10px;
	border-radius: 3px;
}
</style>
<div id="<?php echo $id; ?>" class="noprint">
<div class="test_display"><?php echo $text; ?></div>
<div class="ojs">
<div class="options_panel">
<span class="nowrap"><input type="checkbox"/><span class="btn_edit btn_b">B</span></span>
<span class="nowrap"><input type="checkbox"/><span class="btn_edit btn_i">I</span></span>
</div>
</div>
</div>
<?php head('javascript', '/objectivejs/Objective.js'); ?>
<?php head('javascript', '/objectivejs/Responder.js'); ?>
<?php head('javascript', '/objectivejs/View.js'); ?>
<?php head('javascript', '/objectivejs/Inspector.js'); ?>
<?php head('javascript', '/objectivejs/BooleanInspector.js'); ?>
<script>
function Tester(display, boldInspector, italicInspector) {
	Responder.call(this);

	this._display = display;

	boldInspector.addNextResponder(this);

	this._boldInspector = boldInspector;

	italicInspector.addNextResponder(this);

	this._italicInspector = italicInspector;
}

Tester.prototype = Object.create(Responder.prototype);

Object.defineProperty(Tester.prototype, 'constructor', { value: Tester, enumerable: false, writable: true });

Tester.prototype.inspectorValueChanged = function(sender) {
	if (sender === this._boldInspector)
		this._display.style.fontWeight = sender.get() === true ? 'bold' : 'normal';
	else if (sender === this._italicInspector)
		this._display.style.fontStyle = sender.get() === true ? 'italic' : 'normal';

	return true;
}

Tester.prototype.reset = function() {
	this._boldInspector.reset();
	this._italicInspector.reset();

	this._display.style.fontWeight = this._boldInspector.get() === true ? 'bold' : 'normal';
	this._display.style.fontStyle = this._italicInspector.get() === true ? 'italic' : 'normal';

	return this;
}
</script>
<script>
const boldInspector = new BooleanInspector(true);
const italicInspector = new BooleanInspector();

const container = document.querySelector('#<?php echo $id; ?>');

const display = container.querySelector('.test_display');

const options = container.querySelector('.options_panel');

boldInspector.setManagedWidget(options.children[0].children[0]).resetWidget();
italicInspector.setManagedWidget(options.children[1].children[0]).resetWidget();

const tester = new Tester(display, boldInspector, italicInspector);

tester.reset();
</script>
